apiVersion: apps/v1
kind: Deployment
metadata:
  name: temperature-monitor-api
  labels:
    app: temperature-monitor-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temperature-monitor-api
  template:
    metadata:
      labels:
        app: temperature-monitor-api
    spec:
      containers:
      - name: temperature-monitor-api
        image: temperature-monitor-api:latest
        ports:
        - containerPort: 3000
        env:
        - name: RUST_LOG
          value: "info"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: temperature-monitor-api
spec:
  selector:
    app: temperature-monitor-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
