name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: gitea.zengarden.space
  IMAGE_NAME: ${{ github.repository }}

jobs:

  build-and-push:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Setup Helm
        uses: azure/setup-helm@v4
        with:
          version: '3.12.0'

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.PACKAGE_WRITE_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Lint Helm chart
        run: helm lint ./helm/temperature-monitor-api

      - name: Update Helm values
        run: |
          repo_name=$(echo ${{github.repository}} | cut -d'/' -f2)
          tag=$(echo "${{ steps.meta.outputs.tags }}" | head -n +3 | tail -n 1 | cut -d':' -f2)
          echo "Using tag: $tag"
          helm template $repo_name ./helm/temperature-monitor-api \
            --namespace $repo_name \
            --values ./helm/values-dev.yaml \
            --set image.tag=$tag > manifest.yaml

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: zengarden-space/manifests
          ref: main
          path: manifests
          token: ${{ secrets.CONTENT_WRITE_TOKEN }}
          
      - name: Push changes
        run: |
          repo_name=$(echo ${{github.repository}} | cut -d'/' -f2)
          cd manifests
          git config --local user.name "Gitea Actions Bot"
          git config --local user.email "gitea-actions[bot]@users.noreply.zengarden.space"
          mkdir -p ./$repo_name/dev
          cp ../manifest.yaml ./$repo_name/dev/manifest.yaml
          git add .
          git commit -m "${{ github.repository }}: ${{ github.event.head_commit.message }} ${{github.sha}}"
          git push
